-- 회원정보
DROP TABLE INSA_LOGIN;
CREATE TABLE INSA_LOGIN(
	ID VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	SEX VARCHAR2(2) DEFAULT 'M',
	AGE VARCHAR2(10) NOT NULL,
	BIRTH DATE NOT NULL,
	USER_CONNECTION VARCHAR2(2) DEFAULT 'N',
	AVARTAR CLOB,
	CONSTRAINT SEX_CHK CHECK (SEX IN ('F','M')),
	CONSTRAINT USER_CONNECTION_CHK CHECK (USER_CONNECTION IN ('Y','N'))
);

INSERT INTO INSA_LOGIN VALUES('admin','관리자','1234','F','25','1995/04/18','N','');
INSERT INTO INSA_LOGIN VALUES('jsh','정서희','7777','F','25','1995/04/18','N','');

SELECT * FROM INSA_LOGIN;

-- 게시판
DROP TABLE INSA_BOARD;
CREATE TABLE INSA_BOARD(
	ID VARCHAR2(50) REFERENCES LOGIN(ID) ON DELETE CASCADE,
	BOARD_NUM NUMBER PRIMARY KEY,
	HASH_TAG VARCHAR2(500),
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_IMAGE CLOB,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_PRIVATE VARCHAR2(20) DEFAULT 'EVERYONE',
	CONSTRAINT BOARD_PRIVATE_CHK CHECK (BOARD_PRIVATE IN ('EVERYONE','FRIENDS','PRIVATE'))
);

-- 댓글
DROP TABLE INSA_COMMENT;
CREATE TABLE INSA_COMMENT(
	ID VARCHAR2(50) REFERENCES LOGIN(ID) ON DELETE CASCADE,
	BOARD_NUM NUMBER REFERENCES BOARD(BOARD_NUM) ON DELETE CASCASE,
	COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
	COMMENT_REGDATE DATE NOT NULL
);

-- 방명록
DROP TABLE INSA_GUEST;
CREATE TABLE INSA_GUEST(
	ID VARCHAR2(50) REFERENCES LOGIN(ID) ON DELETE CASCADE,
	GUEST_CONTENT VARCHAR2(4000) NOT NULL
);

-- 친구
DROP TABLE INSA_FRIEND;
CREATE TABLE INSA_FRIEND(
	ID VARCHAR2(50) REFERENCES LOGIN(ID) ON DELETE CASCADE,
	FRIEND_ID VARCHAR2(50)
);

-- 플래너
DROP TABLE INSA_PLANNER;
CREATE TABLE INSA_PLANNER(
	ID VARCHAR2(50) REFERENCES LOGIN(ID) ON DELETE CASCADE,
	PLANNER_DATE DATE NOT NULL,
	PLANNER_CONTENT VARCHAR2(2000) NOT NULL
);